services:
  rabbitmq:
    image: rabbitmq:4.1.2-management
    container_name: rabbitmq
    restart: always
    hostname: "presentation-rabbit"
    ports:
      - 5672:5672
      - 15672:15672
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  rabbitmq-lib:
    driver: local
